### ISSUE TITLE
Awesome project! Could you give the train code to me? Thanks.

### ISSUE THREAD

**Issue by wanghuok** [Nikolai10/mobile-ocr#1]
I want to train the model use my dataset. Thanks.

**Comment by Nikolai10** [comment]
This is a demo project demonstrating the functionality described in "Improving Camera-based Document Analysis with Deep Learning". Additional scripts won't be provided open source.

**Comment by wanghuok** [comment]
OK. But i can not find the paper "Camera-based Document Analysis based on Deep Learning and OCR"

**Comment by Nikolai10** [comment]
The paper will be presented at the ICDD conference (http://sites.conferences.ulbsibiu.ro/icdd/2019/) and subsequently made publicly available.

**Comment by wanghuok** [comment]
Thanks. I'm looking forward to it.
