### ISSUE TITLE
Model link broken

### ISSUE THREAD

**Issue by npow** [Nikolai10/mobile-ocr#3]
I tried downloading the model from mycloud but it's not working. Can you host the model file somewhere else?

![image](https://user-images.githubusercontent.com/206201/77031699-c0365680-6978-11ea-8530-68d1fa93e760.png)

**Comment by Nikolai10** [comment]
Hello npow, 

unfortunately, mycloud seems really unstable... for now please use the following link below:
https://www.dropbox.com/s/8ywndwenfedjab8/xception_10000.h5?dl=0

Kind regards

**Comment by npow** [comment]
Thanks @Nikolai10
